// GENERATED FILE — regenerate with `node scripts/generate-catalog.mjs`.
// Upsert: keys/names come from active workouts; hand-edit video/videoAlternating/tips.
export const EXERCISES = {
  "adductor-and-hamstring-stretch": { name: "Adductor & Hamstring Stretch", tips: "", video: null },
  "adductor-cross": { name: "Adductor Cross", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/adductor-crosses.mp4" },
  "banded-crab-walk": { name: "Banded Crab Walk", tips: "", video: null },
  "bench-press": { name: "Bench Press", tips: "", video: null },
  "bicep-curl": { name: "Bicep Curl", tips: "", video: null },
  "butterfly-bridge": { name: "Butterfly Bridge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/butterfly-bridge.mp4" },
  "butterfly-sit-up": { name: "Butterfly Sit Up", tips: "", video: null },
  "calf-raise": { name: "Calf Raise", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/calf-raise.mp4" },
  "calf-raise-and-curl": { name: "Calf Raise & Curl", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/calf-raise-and-curl.mp4" },
  "crunch": { name: "Crunch", tips: "", video: null },
  "curl-and-press": { name: "Curl & Press", tips: "", video: null },
  "curtsy-lunge": { name: "Curtsy Lunge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/curtsy-lunge.mp4", videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/curtsy-lunge-alt.mp4" },
  "dead-bug": { name: "Dead Bug", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/dead-bugs.mp4" },
  "diagonal-sit-up": { name: "Diagonal Sit Up", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/diagonal-sit-ups.mp4" },
  "fire-hydrant": { name: "Fire Hydrant", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/fire-hydrants.mp4" },
  "fire-hydrant-circle": { name: "Fire Hydrant Circle", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/fire-hydrant-circles.mp4" },
  "flexor-lift": { name: "Flexor Lift", tips: "", video: null, videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/flexor-lifts-alt.mp4" },
  "flexor-up-and-over": { name: "Flexor Up & Over", tips: "", video: null },
  "forward-lunge": { name: "Forward Lunge", tips: "", video: null, videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/forward-lunge-alt.mp4" },
  "forward-lunge-with-twist": { name: "Forward Lunge w/ Twist", tips: "", video: null },
  "forward-reach-squat": { name: "Forward Reach Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/forward-reach-squat.mp4" },
  "front-to-side-raise": { name: "Front to Side Raise", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/front-to-side-raise.mp4" },
  "glute-arc": { name: "Glute Arc", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/glute-arcs.mp4" },
  "glute-bridge": { name: "Glute Bridge", tips: "", video: null },
  "goblet-squat": { name: "Goblet Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/goblet-squat.mp4" },
  "hamstring-bridge": { name: "Hamstring Bridge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/hamstring-bridge.mp4" },
  "heel-tap": { name: "Heel Tap", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/heel-taps.mp4" },
  "hip-circle": { name: "Hip Circle", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/hip-circles.mp4" },
  "hip-dip-plank": { name: "Hip Dip Plank", tips: "", video: null },
  "hip-rocker": { name: "Hip Rocker", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/hip-rockers.mp4" },
  "ice-skater": { name: "Ice Skater", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/ice-skaters.mp4" },
  "jump-squat": { name: "Jump Squat", tips: "", video: null },
  "jump-squat-stabilization": { name: "Jump Squat Stabilization", tips: "", video: null },
  "jumping-jack": { name: "Jumping Jack", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/jumping-jacks.mp4" },
  "knee-assist-plank": { name: "Knee Assist Plank", tips: "", video: null },
  "knee-up": { name: "Knee Up", tips: "", video: null },
  "lat-pull-over": { name: "Lat Pull Over", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/lat-pull-over.mp4" },
  "lateral-pogo": { name: "Lateral Pogo", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/lateral-pogos.mp4" },
  "lying-adductor-cross": { name: "Lying Adductor Cross", tips: "", video: null },
  "mountain-climber": { name: "Mountain Climber", tips: "", video: null },
  "nordic-and-curl": { name: "Nordic & Curl", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/nordic-and-curl.mp4" },
  "oblique-crunch": { name: "Oblique Crunch", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/oblique-crunch.mp4" },
  "pike-push-up": { name: "Pike Push Up", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/pike-push-up.mp4" },
  "plank-hold": { name: "Plank Hold", tips: "", video: null },
  "plank-pike": { name: "Plank Pike", tips: "", video: null },
  "plank-toe-tap": { name: "Plank Toe Tap", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/plank-toe-taps.mp4" },
  "plank-twist": { name: "Plank Twist", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/plank-twist.mp4" },
  "pogo": { name: "Pogo", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/pogos.mp4" },
  "pull-up": { name: "Pull Up", tips: "", video: null },
  "push-up": { name: "Push Up", tips: "", video: null },
  "rdl-row-kickback": { name: "RDL - Row - Kickback", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/rdl-row-kickback.mp4" },
  "rdl-and-row": { name: "RDL & Row", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/rdl-and-row.mp4" },
  "reverse-crunch": { name: "Reverse Crunch", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-crunch.mp4" },
  "reverse-fly": { name: "Reverse Fly", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-fly.mp4", videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-fly-alt.mp4" },
  "reverse-lunge": { name: "Reverse Lunge", tips: "", video: null, videoAlternating: null },
  "reverse-lunge-tap": { name: "Reverse Lunge Tap", tips: "", video: null, videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-lunge-taps-alt.mp4" },
  "romanian-dead-lift": { name: "Romanian Dead Lift", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/romanian-dead-lift.mp4" },
  "row": { name: "Row", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/row.mp4", videoAlternating: null },
  "row-and-kickback": { name: "Row & Kickback", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/row-and-kickback.mp4" },
  "runner-hop": { name: "Runner Hop", tips: "", video: null },
  "russian-twist": { name: "Russian Twist", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/russian-twist.mp4" },
  "shoulder-press": { name: "Shoulder Press", tips: "", video: null },
  "side-lunge": { name: "Side Lunge", tips: "", video: null, videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/side-lunge-alt.mp4" },
  "side-lunge-with-balance-press": { name: "Side Lunge w/ Balance Press", tips: "", video: null },
  "side-lying-leg-lift": { name: "Side Lying Leg Lift", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/side-lying-leg-lift.mp4" },
  "single-arm-row": { name: "Single Arm Row", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-arm-row.mp4", videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-arm-row-alt.mp4" },
  "single-arm-row-with-top-hold": { name: "Single Arm Row w/ Top Hold", tips: "", video: null, videoAlternating: null },
  "single-leg-forward-hop": { name: "Single Leg Forward Hop", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-forward-hops.mp4" },
  "single-leg-glute-bridge": { name: "Single Leg Glute Bridge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-glute-bridge.mp4" },
  "single-leg-glute-bridge-chest-press-hold": { name: "Single Leg Glute Bridge/Chest Press Hold", tips: "", video: null },
  "single-leg-pogo": { name: "Single Leg Pogo", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-pogos.mp4" },
  "single-leg-rdl": { name: "Single Leg RDL", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-rdl.mp4" },
  "skull-crusher": { name: "Skull Crusher", tips: "", video: null },
  "split-squat": { name: "Split Squat", tips: "", video: null },
  "squat-and-press": { name: "Squat & Press", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/squat-and-press.mp4" },
  "squat-jump": { name: "Squat Jump", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/squat-jumps.mp4" },
  "squat-twist": { name: "Squat Twist", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/squat-twist.mp4" },
  "standing-abduction": { name: "Standing Abduction", tips: "", video: null, videoAlternating: null },
  "standing-cat-cow": { name: "Standing Cat/Cow", tips: "", video: null },
  "standing-lateral-leg-lift": { name: "Standing Lateral Leg Lift", tips: "", video: null },
  "static-lunge": { name: "Static Lunge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/static-lunge.mp4" },
  "suitcase-squat": { name: "Suitcase Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/suitcase-squat.mp4" },
  "sumo-goblet-squat": { name: "Sumo Goblet Squat", tips: "", video: null },
  "sumo-squat": { name: "Sumo Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/sumo-squat.mp4" },
  "sumo-squat-curl-press": { name: "Sumo Squat/Curl/Press", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/sumo-squat-curl-press.mp4" },
  "superman-pull-down": { name: "Superman Pull Down", tips: "", video: null },
  "superman-sweep": { name: "Superman Sweep", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/superman-sweep.mp4" },
  "superman-sweep-back": { name: "Superman Sweep Back", tips: "", video: null },
  "tabletop-cat-cow": { name: "Tabletop Cat/Cow", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/tabletop-cat-cow.mp4" },
  "to-the-chin-lift": { name: "To-the-Chin Lift", tips: "", video: null },
  "toe-tap": { name: "Toe Tap", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/toe-taps.mp4" },
  "unilateral-calf-raise-and-curl-hold": { name: "Unilateral Calf Raise & Curl Hold", tips: "", video: null },
  "weighted-bird-dog": { name: "Weighted Bird Dog", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/weighted-bird-dogs.mp4" },
  "y-scaption": { name: "Y Scaption", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/y-scaption.mp4" },
};
