// GENERATED FILE — regenerate with `node scripts/generate-catalog.mjs`.
// Upsert: keys/names come from active workouts; hand-edit video/videoAlternating/tips.
export const EXERCISES = {
  "adductor-and-hamstring-stretch": { name: "Adductor & Hamstring Stretch", tips: "", video: null },
  "adductor-crosses": { name: "Adductor Crosses", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/adductor-crosses.mp4" },
  "banded-crab-walks": { name: "Banded Crab Walks", tips: "", video: null },
  "bench-press": { name: "Bench Press", tips: "", video: null },
  "bicep-curls": { name: "Bicep Curls", tips: "", video: null },
  "butterfly-bridge": { name: "Butterfly Bridge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/butterfly-bridge.mp4" },
  "butterfly-sit-ups": { name: "Butterfly Sit Ups", tips: "", video: null },
  "calf-raise": { name: "Calf Raise", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/calf-raise.mp4" },
  "calf-raise-and-curl": { name: "Calf Raise & Curl", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/calf-raise-and-curl.mp4" },
  "crunch": { name: "Crunch", tips: "", video: null },
  "curl-and-press": { name: "Curl & Press", tips: "", video: null },
  "curtsy-lunge": { name: "Curtsy Lunge", tips: "", video: null, videoAlternating: null },
  "dead-bugs": { name: "Dead Bugs", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/dead-bugs.mp4" },
  "diagonal-sit-ups": { name: "Diagonal Sit Ups", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/diagonal-sit-ups.mp4" },
  "fire-hydrant-circles": { name: "Fire Hydrant Circles", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/fire-hydrant-circles.mp4" },
  "fire-hydrants": { name: "Fire Hydrants", tips: "", video: null },
  "flexor-lifts": { name: "Flexor Lifts", tips: "", video: null, videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/flexor-lifts-alt.mp4" },
  "flexor-up-and-overs": { name: "Flexor Up & Overs", tips: "", video: null },
  "forward-lunge": { name: "Forward Lunge", tips: "", video: null },
  "forward-lunge-with-twist": { name: "Forward Lunge w/ Twist", tips: "", video: null },
  "forward-reach-squat": { name: "Forward Reach Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/forward-reach-squat.mp4" },
  "front-to-side-raise": { name: "Front to Side Raise", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/front-to-side-raise.mp4" },
  "glute-arcs": { name: "Glute Arcs", tips: "", video: null },
  "glute-bridge": { name: "Glute Bridge", tips: "", video: null },
  "goblet-squat": { name: "Goblet Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/goblet-squat.mp4" },
  "hamstring-bridge": { name: "Hamstring Bridge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/hamstring-bridge.mp4" },
  "heel-taps": { name: "Heel Taps", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/heel-taps.mp4" },
  "hip-circles": { name: "Hip Circles", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/hip-circles.mp4" },
  "hip-dip-planks": { name: "Hip Dip Planks", tips: "", video: null },
  "hip-rockers": { name: "Hip Rockers", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/hip-rockers.mp4" },
  "ice-skaters": { name: "Ice Skaters", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/ice-skaters.mp4" },
  "jump-squat": { name: "Jump Squat", tips: "", video: null },
  "jump-squat-stabilization": { name: "Jump Squat Stabilization", tips: "", video: null },
  "jumping-jacks": { name: "Jumping Jacks", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/jumping-jacks.mp4" },
  "knee-assist-plank": { name: "Knee Assist Plank", tips: "", video: null },
  "knee-up": { name: "Knee Up", tips: "", video: null },
  "lat-pull-over": { name: "Lat Pull Over", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/lat-pull-over.mp4" },
  "lateral-pogos": { name: "Lateral Pogos", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/lateral-pogos.mp4" },
  "lying-adductor-crosses": { name: "Lying Adductor Crosses", tips: "", video: null },
  "mountain-climbers": { name: "Mountain Climbers", tips: "", video: null },
  "nordic-and-curl": { name: "Nordic & Curl", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/nordic-and-curl.mp4" },
  "oblique-crunch": { name: "Oblique Crunch", tips: "", video: null },
  "pike-push-up": { name: "Pike Push Up", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/pike-push-up.mp4" },
  "plank-hold": { name: "Plank Hold", tips: "", video: null },
  "plank-pikes": { name: "Plank Pikes", tips: "", video: null },
  "plank-toe-taps": { name: "Plank Toe Taps", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/plank-toe-taps.mp4" },
  "plank-twist": { name: "Plank Twist", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/plank-twist.mp4" },
  "pogos": { name: "Pogos", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/pogos.mp4" },
  "pull-ups": { name: "Pull Ups", tips: "", video: null },
  "push-ups": { name: "Push Ups", tips: "", video: null },
  "rdl-row-kickback": { name: "RDL - Row - Kickback", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/rdl-row-kickback.mp4" },
  "rdl-and-row": { name: "RDL & Row", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/rdl-and-row.mp4" },
  "reverse-crunch": { name: "Reverse Crunch", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-crunch.mp4" },
  "reverse-fly": { name: "Reverse Fly", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-fly.mp4", videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/reverse-fly-alt.mp4" },
  "reverse-lunge": { name: "Reverse Lunge", tips: "", video: null, videoAlternating: null },
  "reverse-lunge-taps": { name: "Reverse Lunge Taps", tips: "", video: null },
  "romanian-dead-lift": { name: "Romanian Dead Lift", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/romanian-dead-lift.mp4" },
  "row": { name: "Row", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/row.mp4", videoAlternating: null },
  "row-and-kickback": { name: "Row & Kickback", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/row-and-kickback.mp4" },
  "row-with-top-hold": { name: "Row w/ Top Hold", tips: "", video: null, videoAlternating: null },
  "runner-hops": { name: "Runner Hops", tips: "", video: null },
  "russian-twist": { name: "Russian Twist", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/russian-twist.mp4" },
  "shoulder-press": { name: "Shoulder Press", tips: "", video: null },
  "side-lunge": { name: "Side Lunge", tips: "", video: null, videoAlternating: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/side-lunge-alt.mp4" },
  "side-lunge-with-balance-press": { name: "Side Lunge w/ Balance Press", tips: "", video: null },
  "side-lying-leg-lift": { name: "Side Lying Leg Lift", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/side-lying-leg-lift.mp4" },
  "single-arm-row": { name: "Single Arm Row", tips: "", video: null },
  "single-arm-top-hold-row": { name: "Single Arm Top Hold Row", tips: "", video: null },
  "single-leg-forward-hops": { name: "Single Leg Forward Hops", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-forward-hops.mp4" },
  "single-leg-glute-bridge": { name: "Single Leg Glute Bridge", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-glute-bridge.mp4" },
  "single-leg-glute-bridge-chest-press-hold": { name: "Single Leg Glute Bridge/Chest Press Hold", tips: "", video: null },
  "single-leg-pogos": { name: "Single Leg Pogos", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/single-leg-pogos.mp4" },
  "single-leg-rdl": { name: "Single Leg RDL", tips: "", video: null },
  "skull-crushers": { name: "Skull Crushers", tips: "", video: null },
  "split-squat": { name: "Split Squat", tips: "", video: null },
  "squat-and-press": { name: "Squat & Press", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/squat-and-press.mp4" },
  "squat-jumps": { name: "Squat Jumps", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/squat-jumps.mp4" },
  "squat-twist": { name: "Squat Twist", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/squat-twist.mp4" },
  "standing-abduction": { name: "Standing Abduction", tips: "", video: null },
  "standing-cat-cow": { name: "Standing Cat/Cow", tips: "", video: null },
  "standing-lateral-leg-lifts": { name: "Standing Lateral Leg Lifts", tips: "", video: null },
  "static-lunge": { name: "Static Lunge", tips: "", video: null },
  "suitcase-squat": { name: "Suitcase Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/suitcase-squat.mp4" },
  "sumo-goblet-squat": { name: "Sumo Goblet Squat", tips: "", video: null },
  "sumo-squat": { name: "Sumo Squat", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/sumo-squat.mp4" },
  "sumo-squat-curl-press": { name: "Sumo Squat/Curl/Press", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/sumo-squat-curl-press.mp4" },
  "superman-pull-down": { name: "Superman Pull Down", tips: "", video: null },
  "superman-sweep-back": { name: "Superman Sweep Back", tips: "", video: null },
  "tabletop-cat-cow": { name: "Tabletop Cat/Cow", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/tabletop-cat-cow.mp4" },
  "to-the-chin-lift": { name: "To-the-Chin Lift", tips: "", video: null },
  "toe-taps": { name: "Toe Taps", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/toe-taps.mp4" },
  "unilateral-calf-raise-and-curl-hold": { name: "Unilateral Calf Raise & Curl Hold", tips: "", video: null },
  "weighted-bird-dogs": { name: "Weighted Bird Dogs", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/weighted-bird-dogs.mp4" },
  "y-scaption": { name: "Y Scaption", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/y-scaption.mp4" },
};
