// GENERATED FILE — regenerate with `node scripts/generate-catalog.mjs`.
// Upsert: keys/names come from active workouts; hand-edit video/videoAlternating/tips.
export const EXERCISES = {
  "adductor-and-hamstring-stretch": { name: "Adductor & Hamstring Stretch", tips: "", video: null },
  "banded-crab-walks": { name: "Banded Crab Walks", tips: "", video: null },
  "bench-press": { name: "Bench Press", tips: "", video: null },
  "bicep-curls": { name: "Bicep Curls", tips: "", video: null },
  "butterfly-bridge": { name: "Butterfly Bridge", tips: "", video: null },
  "butterfly-sit-ups": { name: "Butterfly Sit Ups", tips: "", video: null },
  "calf-raise": { name: "Calf Raise", tips: "", video: null },
  "calf-raise-and-curl": { name: "Calf Raise & Curl", tips: "", video: null },
  "crunch": { name: "Crunch", tips: "", video: null },
  "curl-and-press": { name: "Curl & Press", tips: "", video: null },
  "curtsy-lunge": { name: "Curtsy Lunge", tips: "", video: null, videoAlternating: null },
  "dead-bugs": { name: "Dead Bugs", tips: "", video: null },
  "diagonal-sit-ups": { name: "Diagonal Sit Ups", tips: "", video: null },
  "fire-hydrant-circles": { name: "Fire Hydrant Circles", tips: "", video: null },
  "fire-hydrants": { name: "Fire Hydrants", tips: "", video: null },
  "flexor-lifts": { name: "Flexor Lifts", tips: "", video: null, videoAlternating: null },
  "flexor-up-and-overs": { name: "Flexor Up & Overs", tips: "", video: null },
  "forward-lunge": { name: "Forward Lunge", tips: "", video: null, videoAlternating: null },
  "forward-lunge-with-twist": { name: "Forward Lunge w/ Twist", tips: "", video: null },
  "forward-reach-squat": { name: "Forward Reach Squat", tips: "", video: null },
  "front-to-side-raise": { name: "Front to Side Raise", tips: "", video: null },
  "glute-arcs": { name: "Glute Arcs", tips: "", video: null },
  "glute-bridge": { name: "Glute Bridge", tips: "", video: null },
  "goblet-squat": { name: "Goblet Squat", tips: "", video: null },
  "hamstring-bridge": { name: "Hamstring Bridge", tips: "", video: null },
  "heel-taps": { name: "Heel Taps", tips: "", video: null },
  "hip-circles": { name: "Hip Circles", tips: "", video: null },
  "hip-dip-planks": { name: "Hip Dip Planks", tips: "", video: null },
  "hip-rockers": { name: "Hip Rockers", tips: "", video: null },
  "ice-skaters": { name: "Ice Skaters", tips: "", video: null },
  "jumping-jacks": { name: "Jumping Jacks", tips: "", video: null },
  "knee-assist-plank": { name: "Knee Assist Plank", tips: "", video: null, videoAlternating: null },
  "knee-up": { name: "Knee Up", tips: "", video: null },
  "lat-pull-over": { name: "Lat Pull Over", tips: "", video: null },
  "lateral-pogos": { name: "Lateral Pogos", tips: "", video: null },
  "lying-adductor-crosses": { name: "Lying Adductor Crosses", tips: "", video: null },
  "mountain-climbers": { name: "Mountain Climbers", tips: "", video: null },
  "nordic-and-curl": { name: "Nordic & Curl", tips: "", video: null },
  "oblique-crunch": { name: "Oblique Crunch", tips: "", video: null },
  "pike-push-up": { name: "Pike Push Up", tips: "", video: null },
  "plank-hold": { name: "Plank Hold", tips: "", video: null },
  "plank-pikes": { name: "Plank Pikes", tips: "", video: null },
  "plank-toe-taps": { name: "Plank Toe Taps", tips: "", video: null },
  "plank-twist": { name: "Plank Twist", tips: "", video: null },
  "pogos": { name: "Pogos", tips: "", video: null },
  "pull-ups": { name: "Pull Ups", tips: "", video: null },
  "push-ups": { name: "Push Ups", tips: "", video: null },
  "rdl-row-kickback": { name: "RDL - Row - Kickback", tips: "", video: null },
  "rdl-and-row": { name: "RDL & Row", tips: "", video: null },
  "reverse-crunch": { name: "Reverse Crunch", tips: "", video: null },
  "reverse-fly": { name: "Reverse Fly", tips: "", video: null, videoAlternating: null },
  "reverse-lunge": { name: "Reverse Lunge", tips: "", video: null, videoAlternating: null },
  "reverse-lunge-taps": { name: "Reverse Lunge Taps", tips: "", video: null },
  "romanian-dead-lift": { name: "Romanian Dead Lift", tips: "", video: null },
  "row": { name: "Row", tips: "", video: null },
  "row-and-kickback": { name: "Row & Kickback", tips: "", video: null },
  "row-with-top-hold": { name: "Row w/ Top Hold", tips: "", video: null, videoAlternating: null },
  "runner-hops": { name: "Runner Hops", tips: "", video: null },
  "russian-twist": { name: "Russian Twist", tips: "", video: null },
  "shoulder-press": { name: "Shoulder Press", tips: "", video: null },
  "side-lunge": { name: "Side Lunge", tips: "", video: null, videoAlternating: null },
  "side-lunge-with-balance-press": { name: "Side Lunge w/ Balance Press", tips: "", video: null },
  "side-lying-leg-lift": { name: "Side Lying Leg Lift", tips: "", video: null },
  "single-arm-row": { name: "Single Arm Row", tips: "", video: null, videoAlternating: null },
  "single-arm-top-hold-row": { name: "Single Arm Top Hold Row", tips: "", video: null },
  "single-leg-forward-hops": { name: "Single Leg Forward Hops", tips: "", video: null },
  "single-leg-glute-bridge": { name: "Single Leg Glute Bridge", tips: "", video: null },
  "single-leg-glute-bridge-chest-press-hold": { name: "Single Leg Glute Bridge/Chest Press Hold", tips: "", video: null },
  "single-leg-pogos": { name: "Single Leg Pogos", tips: "", video: null },
  "single-leg-rdl": { name: "Single Leg RDL", tips: "", video: null },
  "skull-crushers": { name: "Skull Crushers", tips: "", video: null },
  "split-squat": { name: "Split Squat", tips: "", video: null },
  "squat-and-press": { name: "Squat & Press", tips: "", video: null },
  "squat-jumps": { name: "Squat Jumps", tips: "", video: null },
  "squat-twist": { name: "Squat Twist", tips: "", video: null },
  "standing-abduction": { name: "Standing Abduction", tips: "", video: null, videoAlternating: null },
  "standing-cat-cow": { name: "Standing Cat/Cow", tips: "", video: null },
  "standing-lateral-leg-lifts": { name: "Standing Lateral Leg Lifts", tips: "", video: null },
  "static-lunge": { name: "Static Lunge", tips: "", video: null },
  "suitcase-squat": { name: "Suitcase Squat", tips: "", video: null },
  "sumo-goblet-squat": { name: "Sumo Goblet Squat", tips: "", video: null },
  "sumo-squat": { name: "Sumo Squat", tips: "", video: null },
  "sumo-squat-curl-press": { name: "Sumo Squat/Curl/Press", tips: "", video: null },
  "superman-pull-down": { name: "Superman Pull Down", tips: "", video: null },
  "superman-sweep-back": { name: "Superman Sweep Back", tips: "", video: null },
  "tabletop-cat-cow": { name: "Tabletop Cat/Cow", tips: "", video: null },
  "to-the-chin-lift": { name: "To-the-Chin Lift", tips: "", video: null },
  "toe-taps": { name: "Toe Taps", tips: "", video: null },
  "unilateral-calf-raise-and-curl-hold": { name: "Unilateral Calf Raise & Curl Hold", tips: "", video: null },
  "weighted-bird-dogs": { name: "Weighted Bird Dogs", tips: "", video: "https://6a94koge7mtrmdjd.public.blob.vercel-storage.com/exercises/weighted-bird-dogs.mp4" },
  "y-scaption": { name: "Y Scaption", tips: "", video: null },
};
