// Upserts workouts/exercises.data.js from the ACTIVE workouts (those exported by
// workouts/index.js) via mergeCatalog: preserves hand-entered values, ADDS + LOGS
// new movements, keeps + warns about unused ones. Safe to re-run.
// Run: node scripts/generate-catalog.mjs
import { writeFileSync, existsSync } from "fs";
import { pathToFileURL } from "url";
import path from "path";
import { WORKOUTS } from "../workouts/index.js";
import { slugify } from "../workouts/exercises.js";
import { deriveCore } from "./lib/normalize-exercises.mjs";
import { mergeCatalog } from "./lib/merge-catalog.mjs";

// 1. movements the active workouts require: slug -> { name, hasAlt }
const required = {};
for (const w of WORKOUTS) {
  for (const phase of w.phases) {
    for (const circuit of phase.circuits) {
      for (const ex of circuit.exercises) {
        if (ex.name === "Rest") continue;
        const d = deriveCore(ex.name);
        if (!d) throw new Error(`Active workout "${w.name}" uses deleted movement "${ex.name}"`);
        const slug = slugify(d.core);
        if (!required[slug]) required[slug] = { name: d.core, hasAlt: false };
        if (d.side === "Alternating") required[slug].hasAlt = true;
      }
    }
  }
}

// 2. load existing catalog + merge (upsert)
const dataPath = path.resolve("workouts/exercises.data.js");
let existing = {};
if (existsSync(dataPath)) ({ EXERCISES: existing } = await import(pathToFileURL(dataPath).href));
const { merged, added, orphans } = mergeCatalog(existing, required);

// 3. emit, sorted by display name
const emit = (e) => {
  const parts = [`name: ${JSON.stringify(e.name)}`, `tips: ${JSON.stringify(e.tips ?? "")}`, `video: ${JSON.stringify(e.video ?? null)}`];
  if ("videoAlternating" in e) parts.push(`videoAlternating: ${JSON.stringify(e.videoAlternating ?? null)}`);
  return `{ ${parts.join(", ")} }`;
};
const body = Object.entries(merged)
  .sort((a, b) => a[1].name.localeCompare(b[1].name))
  .map(([slug, e]) => `  ${JSON.stringify(slug)}: ${emit(e)},`)
  .join("\n");

writeFileSync(dataPath, `// GENERATED FILE — regenerate with \`node scripts/generate-catalog.mjs\`.
// Upsert: keys/names come from active workouts; hand-edit video/videoAlternating/tips.
export const EXERCISES = {
${body}
};
`);

// 4. write a local-only (gitignored) worklist of movements still missing a clip
const byName = (a, b) => a[1].name.localeCompare(b[1].name);
const needPrimary = Object.entries(merged).filter(([, e]) => !e.video).sort(byName);
const needAlt = Object.entries(merged)
  .filter(([, e]) => "videoAlternating" in e && !e.videoAlternating)
  .sort(byName);
writeFileSync(path.resolve("docs/exercise-todo.md"), `# Exercises still needing video

_Generated by \`scripts/generate-catalog.mjs\` — do not edit by hand._

## Missing primary clip (${needPrimary.length})

${needPrimary.map(([slug, e]) => `- [ ] ${e.name} (\`${slug}.mp4\`)`).join("\n") || "_none — all filmed 🎉_"}

## Missing alternating clip (${needAlt.length})

${needAlt.map(([slug, e]) => `- [ ] ${e.name} (\`${slug}-alt.mp4\`)`).join("\n") || "_none_"}
`);

console.log(`Wrote ${Object.keys(merged).length} exercises to workouts/exercises.data.js`);
console.log(added.length ? `  + ${added.length} new: ${added.join(", ")}` : "  no new movements");
if (orphans.length) console.log(`  ! ${orphans.length} no longer used (kept): ${orphans.map((s) => existing[s].name).sort().join(", ")}`);
console.log(`  todo → docs/exercise-todo.md (${needPrimary.length} primary, ${needAlt.length} alt still needed)`);
